### ISSUE TITLE
Fix cargo-clippy warnings

### ISSUE THREAD

**Issue by meltinglava** [gura-conf/gura-rs-parser#2]
[clippy](https://github.com/rust-lang/rust-clippy) is a good linter. Ran it an it comes up with roughly 50 warnings. Should be marked as a beginner issue, as almost any of these lints are good to learn rust.

**Comment by Genarito** [comment]
Hi @meltinglava!

First of all, thank you for this issue and the PR. One of the best aspects of open source software is what you can learn from the users in the community, I had forgotten about Clippy completely. I'll be taking a look at it later when I finish some stuff here and apply the necessary changes.

Thanks again and best regards!

**Comment by Genarito** [comment]
Fixed in [0.3.0](https://crates.io/crates/gura)! :D

**Comment by Genarito** [comment]
No it's not... I'm checking again with the `-D` flag

**Comment by Genarito** [comment]
I was using Rust 1.53 and Github Actions was using 1.54. I've updated my local version and fixed all the Clippy warnings in 0.3.1
