### ISSUE TITLE
Optional Serde support

### ISSUE THREAD

**Issue by fmease** [gura-conf/gura-rs-parser#7]
Hey, I _really_ appreciate this project (the format itself and this implementation) :heart: and I plan to use it in one of my personal projects. However as of right now, this library is not as ergonomic as it could be which is why I am currently holding off on using it. Specifically, it lacks integration with [serde](https://lib.rs/crates/serde).

With Serde support, one could write things like:

```rust
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug)]
struct Point { x: i32, y: i32 }

fn main() {
    let point = Point { x: 1, y: 2 };

    let serialized = gura::to_string(&point).unwrap();
    let deserialized: Point = gura::from_str(&serialized).unwrap();
}
```

That is, without much boilerplate, one can (de-)serialize almost arbitrary structs and enums to/from Gura. The parsing and rendering in the user code gets hidden away by Serde.

Yet I have to mention that Serde is quite a big dependency. Thus it's advisable to make use of Rust's/Cargo's feature system and allow the user to either opt in or opt out of Serde (depending on your preference as the library author). For prior art, take a look at [serde_json](https://lib.rs/crates/serde_json).

Serde is well known in the Rust community and for every major format there exists a crate with Serde support: JSON, XML, YAML, TOML, JSON5, BSON, RON, you name it.

If I had more time at hand, I would definitely implement this by myself and make a pull request but sadly I do not.

Thank you for your work!

**Comment by Genarito** [comment]
Hi @fmease!

First of all, thank you very much for your support of Gura. We are glad to hear that you find it useful and want to use it for your future projects!

Regarding what you say about Serde, I totally agree. In issue #5 where a user asked how he could generate structures quickly, I made it clear that the process is going to be tedious until the implementation of Serde, which we have considered from the beginning as indispensable for Gura to be usable from Rust, is finished.

This week is complicated, but next week I will be working on it. I'll let you know as soon as Serde-Gura is available.

Greetings and success with your new projects! 😄
